title: IEOR 8100
description: Topics in Reinforcement Learning ..
theme: jekyll-theme-slate
navbar-links:
  Author's home: "http://deanattali.com"
show_downloads: false
google_analytics:
github_button_location_top_navbar: true
copyright:
footer:


