title: IEOR 8100
description: Topics in Reinforcement Learning 
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
github_button_location_top_navbar: true
copyright:
footer:

navbar-links:
  Author's home: "http://deanattali.com"
